# Guest OS timezone
timezone: Europe/Moscow

# Are we need check box updates for every 'vagrant up'?
box_check_update: false

# Virtual machine name
machine_name: inkloc

# Virtual machine IP
ip: 192.168.83.110

# Virtual machine CPU cores number
cpus: 2

# Virtual machine RAM
memory: 4096


# Откуда запуска NetCat
api: './api'
dump: './broker'
web: './web'
